### ISSUE TITLE
Define LAYERSERIES_COMPAT_zeroc in layer.conf?

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/meta-zeroc#1]
When building with Yocto 2.6, I'm now seeing this warning:
```
WARNING: Layer zeroc should set LAYERSERIES_COMPAT_zeroc in its conf/layer.conf file to list the core layer names it is compatible with.
```

https://www.yoctoproject.org/docs/2.6/ref-manual/ref-manual.html#var-LAYERSERIES_COMPAT

**Comment by externl** [comment]
`2.4` (`rocko`) is the latest we support. For `3.7.2` we should do the work on `master`, then create a new branch for `2.6` (`thud`).

**Comment by pepone** [comment]
Fixed in master
